In [1]:
from sklearn.datasets import load_iris

def train_test_split(features, label, train_size):
    split_len = int((train_size * (len(label)-1)) / 100)
    x_train = features[:split_len]
    y_train = label[:split_len]
    x_test = features[split_len:]
    y_test = label[split_len:]
    return x_train, x_test, y_train, y_test

iris = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, train_size=80)

In [2]:
x_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
def fit(x, y):
    assert len(x) == len(y)

fit(x_train, y_train)

In [5]:
import numpy as np

def distance(X1, X2):
    X1, X2 = np.array(X1), np.array(X2)
    distance = 0
    for i in range(len(X1) - 1):
        distance += (X1[i] - X2[i]) ** 2
    return np.sqrt(distance)

In [6]:
def predict(x_train, x_test, y_train, k):
    predicts = []
    for i in range(len(x_test)):
        distances = []
        neighbors = []
        for j in range(len(x_train)):
            dist = distance(x_train[j], x_test[i])
            distances.append([dist, j])
        distances.sort()
        distances = distances[0:k]
        for _, j in distances:
            neighbors.append(y_train[j])
        ans = max(neighbors)
        predicts.append(ans)
    return predicts

k = 3
predictions = predict(x_train, x_test, y_train, k=k)

In [7]:
np.array(predictions)

array([2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
def score(predictions, y_test):
    return (predictions == y_test).sum() / len(y_test)

accuracy = score(predictions, y_test)

In [10]:
accuracy

0.8709677419354839